# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.31

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/ki/classes/cop3504c/project_2

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/ki/classes/cop3504c/project_2

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake cache editor..."
	/usr/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/ki/classes/cop3504c/project_2/CMakeFiles /home/ki/classes/cop3504c/project_2//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/ki/classes/cop3504c/project_2/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named the-sweeper

# Build rule for target.
the-sweeper: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 the-sweeper
.PHONY : the-sweeper

# fast build rule for target.
the-sweeper/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/the-sweeper.dir/build.make CMakeFiles/the-sweeper.dir/build
.PHONY : the-sweeper/fast

src/config.o: src/config.cpp.o
.PHONY : src/config.o

# target to build an object file
src/config.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/the-sweeper.dir/build.make CMakeFiles/the-sweeper.dir/src/config.cpp.o
.PHONY : src/config.cpp.o

src/config.i: src/config.cpp.i
.PHONY : src/config.i

# target to preprocess a source file
src/config.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/the-sweeper.dir/build.make CMakeFiles/the-sweeper.dir/src/config.cpp.i
.PHONY : src/config.cpp.i

src/config.s: src/config.cpp.s
.PHONY : src/config.s

# target to generate assembly for a file
src/config.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/the-sweeper.dir/build.make CMakeFiles/the-sweeper.dir/src/config.cpp.s
.PHONY : src/config.cpp.s

src/game.o: src/game.cpp.o
.PHONY : src/game.o

# target to build an object file
src/game.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/the-sweeper.dir/build.make CMakeFiles/the-sweeper.dir/src/game.cpp.o
.PHONY : src/game.cpp.o

src/game.i: src/game.cpp.i
.PHONY : src/game.i

# target to preprocess a source file
src/game.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/the-sweeper.dir/build.make CMakeFiles/the-sweeper.dir/src/game.cpp.i
.PHONY : src/game.cpp.i

src/game.s: src/game.cpp.s
.PHONY : src/game.s

# target to generate assembly for a file
src/game.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/the-sweeper.dir/build.make CMakeFiles/the-sweeper.dir/src/game.cpp.s
.PHONY : src/game.cpp.s

src/leaderboard.o: src/leaderboard.cpp.o
.PHONY : src/leaderboard.o

# target to build an object file
src/leaderboard.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/the-sweeper.dir/build.make CMakeFiles/the-sweeper.dir/src/leaderboard.cpp.o
.PHONY : src/leaderboard.cpp.o

src/leaderboard.i: src/leaderboard.cpp.i
.PHONY : src/leaderboard.i

# target to preprocess a source file
src/leaderboard.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/the-sweeper.dir/build.make CMakeFiles/the-sweeper.dir/src/leaderboard.cpp.i
.PHONY : src/leaderboard.cpp.i

src/leaderboard.s: src/leaderboard.cpp.s
.PHONY : src/leaderboard.s

# target to generate assembly for a file
src/leaderboard.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/the-sweeper.dir/build.make CMakeFiles/the-sweeper.dir/src/leaderboard.cpp.s
.PHONY : src/leaderboard.cpp.s

src/main.o: src/main.cpp.o
.PHONY : src/main.o

# target to build an object file
src/main.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/the-sweeper.dir/build.make CMakeFiles/the-sweeper.dir/src/main.cpp.o
.PHONY : src/main.cpp.o

src/main.i: src/main.cpp.i
.PHONY : src/main.i

# target to preprocess a source file
src/main.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/the-sweeper.dir/build.make CMakeFiles/the-sweeper.dir/src/main.cpp.i
.PHONY : src/main.cpp.i

src/main.s: src/main.cpp.s
.PHONY : src/main.s

# target to generate assembly for a file
src/main.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/the-sweeper.dir/build.make CMakeFiles/the-sweeper.dir/src/main.cpp.s
.PHONY : src/main.cpp.s

src/welcome_screen.o: src/welcome_screen.cpp.o
.PHONY : src/welcome_screen.o

# target to build an object file
src/welcome_screen.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/the-sweeper.dir/build.make CMakeFiles/the-sweeper.dir/src/welcome_screen.cpp.o
.PHONY : src/welcome_screen.cpp.o

src/welcome_screen.i: src/welcome_screen.cpp.i
.PHONY : src/welcome_screen.i

# target to preprocess a source file
src/welcome_screen.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/the-sweeper.dir/build.make CMakeFiles/the-sweeper.dir/src/welcome_screen.cpp.i
.PHONY : src/welcome_screen.cpp.i

src/welcome_screen.s: src/welcome_screen.cpp.s
.PHONY : src/welcome_screen.s

# target to generate assembly for a file
src/welcome_screen.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/the-sweeper.dir/build.make CMakeFiles/the-sweeper.dir/src/welcome_screen.cpp.s
.PHONY : src/welcome_screen.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... the-sweeper"
	@echo "... src/config.o"
	@echo "... src/config.i"
	@echo "... src/config.s"
	@echo "... src/game.o"
	@echo "... src/game.i"
	@echo "... src/game.s"
	@echo "... src/leaderboard.o"
	@echo "... src/leaderboard.i"
	@echo "... src/leaderboard.s"
	@echo "... src/main.o"
	@echo "... src/main.i"
	@echo "... src/main.s"
	@echo "... src/welcome_screen.o"
	@echo "... src/welcome_screen.i"
	@echo "... src/welcome_screen.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

